version: "3"

services:
  laconicdnode0:
    container_name: laconicdnode0
    image: "laconicd/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-laconicd.log}
    volumes:
      - ./localnet-setup/node0/laconicd:/laconicd:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  laconicdnode1:
    container_name: laconicdnode1
    image: "laconicd/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-laconicd.log}
    volumes:
      - ./localnet-setup/node1/laconicd:/laconicd:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  laconicdnode2:
    container_name: laconicdnode2
    image: "laconicd/node"
    environment:
      - ID=2
      - LOG=${LOG:-laconicd.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/laconicd:/laconicd:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  laconicdnode3:
    container_name: laconicdnode3
    image: "laconicd/node"
    environment:
      - ID=3
      - LOG=${LOG:-laconicd.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/laconicd:/laconicd:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
