name: Deploy Contract
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - name: Test contract
        run: |
          make contract-tools
          # This seems to be an empty placeholder.
          make test-contract
