name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  sdk_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout laconic-sdk
        uses: actions/checkout@v3
        with:
          path: "./laconic-sdk/"
          repository: cerc-io/laconic-sdk
          fetch-depth: 0
          ref: main
      - name: Environment
        run: ls -tlh && env

      - name: Build laconicd container
        working-directory: tests/sdk_tests
        run: ./build-laconicd-container.sh

      - name: Build laconic-sdk container
        working-directory: laconic-sdk
        run: ./scripts/build-sdk-test-container.sh

      - name: Start containers (expiry enabled)
        working-directory: tests/sdk_tests
        env:
          TEST_REGISTRY_EXPIRY: true
        run: docker compose up -d

      - name: Run nameservice expiry tests
        working-directory: tests/sdk_tests
        run: ./run-tests.sh test:nameservice-expiry
