name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  test-importer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - name: test-importer
        run: |
          make test-import
